### ISSUE TITLE
405 error is showing

### ISSUE THREAD

**Issue by binitkumar26** [dtqoku/woocommerce-raiffeisen-payment-gateway#1]
When i am integrate woocommerce-raiffeisen-payment-gateway getting 405 error how to resolve this error .

**Comment by dtqoku** [comment]
Hello, this only works with Albanian Raiffeisen bank.

**Comment by klevismiho** [comment]
Many thanks for this plugin. 
If it helps somebody, the merchantid.pem file needs to be put on /cert folder by default.
